### ISSUE TITLE
🤐 Compression / décompression LZMA avec mot de passe

### ISSUE THREAD

**Issue by Dougniel** [opt-nc/j7zip#1]
## Requirements

 -☝️ Command line tool
 - 🧰 Similar to `p7zip`

------------------------------

## Actions

- [x] mplement compress/decompress
- [x] decompress encrypted with password
- [x] hack compress encrypted with password (as it not supported by Apache Commons Compress) 👉🏼 [this branch](https://github.com/opt-nc/j7zip/tree/hack-commons-compress-with-encryption)
- [x] Make a [PR](https://github.com/apache/commons-compress/pull/332) on Apache Commons Compress project - and wait ([COMPRESS-633](https://issues.apache.org/jira/browse/COMPRESS-633))
- [ ] ~Get the last version of Apache Commons Compress with the feature 🎉~

**Comment by Dougniel** [comment]
🤞🏼[PR](https://github.com/apache/commons-compress/pull/332) prête sur le GitHub mirror de Apache Commons Compress + ticket [JIRA](https://issues.apache.org/jira/browse/COMPRESS-633)

**Comment by adriens** [comment]
@Dougniel , petite typo : `Encyrption ` -> `Encryption` 😅

**Comment by Dougniel** [comment]
🤔
<img width="999" alt="image" src="https://user-images.githubusercontent.com/39691264/204378771-4c4593a1-2d3e-4c99-a0ca-925e8425f829.png">

**Comment by Dougniel** [comment]
👉🏼 https://github.com/apache/commons-compress/pull/332#issuecomment-1330195038

⏸️ Waiting for CI results

**Comment by adriens** [comment]
Classe :sunglasses: 
![image](https://user-images.githubusercontent.com/5235127/204466107-d50e5fe4-2688-47ef-b577-1db423dea80a.png)

**Comment by Dougniel** [comment]
PR Mergée 🎉

⏸️ En attente de release

**Comment by adriens** [comment]
OH :heavy_heart_exclamation: :muscle: :rocket: :clap: :clap:

**Comment by adriens** [comment]
Excellent !!!! Bravo @Dougniel :weight_lifting_man:

**Comment by Dougniel** [comment]
<img width="947" alt="image" src="https://user-images.githubusercontent.com/39691264/208773763-ebf7d2c9-3586-434c-9db8-0fb36a4b5674.png">

Tu as été relancé sur le sujet @adriens ? Je crois qu'il va peut-être falloir livrer non ?

**Comment by adriens** [comment]
Non, pas été relancé car pu rl'instant on a un contournement.
Mais on pourrait livrer en attendant et attaqer la partie delivery continue/packaging avec JReelaser.

Une fois la PR mergée, ce sera "une nouvelle release" : qu'en dis-tu ?

**Comment by Dougniel** [comment]
> Non, pas été relancé car pu rl'instant on a un contournement. Mais on pourrait livrer en attendant et attaqer la partie delivery continue/packaging avec JReelaser.
> 
> Une fois la PR mergée, ce sera "une nouvelle release" : qu'en dis-tu ?

Oui on peut faire ça, ce sera transparent pour les utilisateurs

**Comment by adriens** [comment]
Yep, tout à fait 🚀

**Comment by adriens** [comment]
Surtotu qu'il y a pas mal de boulot côté CI et packaging

**Comment by Dougniel** [comment]
Première version releasée
