### ISSUE TITLE
:zap: Cannot make jar executable (cannot execute binary file: Exec format error)

### ISSUE THREAD

**Issue by adriens** [opt-nc/j7zip#14]
# :grey_question: Context

I need to make the jar executable but I cannot achieve this.

Here are the steps to reproduce : 

```shell
export J7ZIP_VERSION=v1.0.0
curl -LO https://github.com/opt-nc/j7zip/releases/download/$J7ZIP_VERSION/j7zip.jar
chmod +x j7zip.jar
./j7zip.jar
java -jar j7zip.jar
```

![image](https://user-images.githubusercontent.com/5235127/208856430-7e4fd4e1-735e-4392-b9a9-2aa01d4d344b.png)

# :dart: Action

Please let me know what should be done to make it possible to run the `jar` without having to call `java -jar`... or if not possible provide a `j7zip.sh` in the repo that I could make executable.

**Comment by adriens** [comment]
I'm preparing a dumb `.sh` that does the job

**Comment by Dougniel** [comment]
Maybe I didn't understand you request, but a JAR cannot be executed directly without [`java`](https://docs.oracle.com/en/java/javase/13/docs/specs/man/java.html)

**Comment by adriens** [comment]
I [meant the following thing](https://www.javatpoint.com/how-to-make-an-executable-jar-file-in-java)(assuming we have a `java` runtime properly set)

```
chmod u+x hello.jar
./hello.jar
```

:information_source: Sometimes we use it on Spring Boot

**Comment by Dougniel** [comment]
> I [meant the following thing](https://www.javatpoint.com/how-to-make-an-executable-jar-file-in-java)(assuming we have a `java` runtime properly set)

The purpose of this documentation is to explain how to make an executable JAR versus a lib JAR (with MANIFEST.MF)

> ℹ️ Sometimes we use it on Spring Boot

Never seen that before, you need `java -jar ..'. Do you have some example ?

**Comment by adriens** [comment]
:point_down: 

- https://github.com/remkop/picocli/discussions/1903

**Comment by Dougniel** [comment]
> 👇
> 
> * [Really executable JAR with spring-boot-maven-plugin remkop/picocli#1903](https://github.com/remkop/picocli/discussions/1903)

Have you tested it ?

Look at the docs please : https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#goals-repackage

![image](https://user-images.githubusercontent.com/39691264/209483168-c2ba6035-6c7c-4936-a605-f63a2ee83f1f.png)

**Comment by adriens** [comment]
We'll talk about this at our SCRUM this afternoon.

**Comment by adriens** [comment]
As discuused today. Abandonned because too much OS specfic
