### ISSUE TITLE
:shield:  Maven > Enforce build with Java 8 :older_man: 

### ISSUE THREAD

**Issue by adriens** [opt-nc/j7zip#26]
The main "feature" of the lib is to only require Java 8 for legacy systems.

To make sure the project is always built with a proper SDK version, use [Maven Enforcer](https://maven.apache.org/enforcer/maven-enforcer-plugin/)

**Comment by Dougniel** [comment]
Why this is not enough in the `pom.xml` for you ? : 

```xml
    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
       ...
    </properties>
```

**Comment by adriens** [comment]
Actually my runtime is the following : 

<pre><font color="#5FD700">❯</font> java -version
openjdk version &quot;17.0.5&quot; 2022-10-18
OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8)
OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode, sharing)</pre>

... and **I would like it to fail to force me to build it with the legacy java runtime**... but I cal achieve the build without any problem : 

![image](https://user-images.githubusercontent.com/5235127/209485034-fcf69c42-2c06-412a-bbfb-7be4dc02da1e.png)

**Comment by Dougniel** [comment]
> Actually my runtime is the following :
> 
> ❯ java -version
> openjdk version "17.0.5" 2022-10-18
> OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8)
> OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode, sharing)
> ... and **I would like it to fail to force me to build it with the legacy java runtime**... but I cal achieve the build without any problem :

Why do you want that ? 
`Javac` is designed to be backward compatible (through `-target` options), what do you need more ?

**Comment by adriens** [comment]
... what if someone want to use the `Record` in a PR ?

**Comment by Dougniel** [comment]
> ... what if someone want to use the `Record` in a PR ?

He will get a compilation error on CI (and locally) because of [this](https://github.com/opt-nc/j7zip/issues/26#issuecomment-1364746059)

**Comment by adriens** [comment]
👍
